apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2018-12-22T14:14:40Z
  generation: 1
  labels:
    run: example
  name: example
  namespace: default
  resourceVersion: "3191"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/example
  uid: eba2bf10-05f3-11e9-9204-0800279b3da4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: example
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: example
    spec:
      containers:
      - image: nginx:1.13.5-alpine
        imagePullPolicy: IfNotPresent
        name: example
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
